name: portfolio
description: My portfolio :)

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.2.3+13

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  delayed_display: ^2.0.0
  flip_card:
    git:
      url: https://github.com/BrunoJurkovic/flip_card.git
      ref: 061720d21bf68c802439db49c520a02f7b733076
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  markdown: ^7.2.2
  performance: ^0.1.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  slimy_card:
    git: https://github.com/ciriousjoker/SlimyCard-Animated-Flutter-Package.git
  timeline_tile: ^2.0.0
  url_launcher: ^6.2.6

dev_dependencies:
  build_runner: ^2.4.10
  flutter_test:
    sdk: flutter
  lint: ^2.3.0

flutter:
  # NOTE: ./fonts/src/README.ME
  uses-material-design: false

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/projects.json

  fonts:
    - family: Exo2
      fonts:
        - asset: fonts/Exo2-Regular.ttf
    - family: BrandIconsMinified
      fonts:
        - asset: fonts/BrandIconsMinified.ttf
    - family: MaterialIconsMinified
      fonts:
        - asset: fonts/MaterialIconsMinified.ttf
    - family: Catamaran
      fonts:
        - asset: fonts/Catamaran/static/Catamaran-Light.ttf
          weight: 200
        - asset: fonts/Catamaran/static/Catamaran-Regular.ttf
          weight: 400
        - asset: fonts/Catamaran/static/Catamaran-Medium.ttf
          weight: 500
